BOT_DEPTH: int = 1000
BOARD_SIZE: int = 9
INITIAL_WALL_COUNT: int = 10
WIN_SCORE: int = 1000
MAX_PATH_COST: int = 999
INFINITY: float = float("inf")

VERTICAL_WALL = "║"
HORIZONTAL_WALL = "═"

VERTICAL_CELL_BOUNDARY = "|"
HORIZONTAL_CELL_BOUNDARY = "─"
